#AUTOGENERATED! DO NOT EDIT! File to edit: dev/dagmm_main.ipynb (unless otherwise specified).

__all__ = ['str2bool', 'main']

#Cell
import os
from .solver import Solver
from .data_loader import get_loader
from torch.backends import cudnn
from .utils import *
from ..notebook.export import *

#Cell
def str2bool(v):
    return v.lower() in ('true')

def main(config):
    # For fast training
    cudnn.benchmark = True

    # Create directories if not exist
    mkdir(config.log_path)
    mkdir(config.model_save_path)

    data_loader = get_loader(config.data_path, batch_size=config.batch_size, mode=config.mode)

    # Solver
    solver = Solver(data_loader, vars(config))

    if config.mode == 'train':
        solver.train()
    elif config.mode == 'test':
        solver.test()

    return solver