#AUTOGENERATED! DO NOT EDIT! File to edit: dev/dagmm_utils.ipynb (unless otherwise specified).

__all__ = ['to_var', 'mkdir']

#Cell
import os
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.autograd import Variable
import numpy as np
import glob
from ..imports import *
from ..notebook.export import *

#Cell
def to_var(x):
    if torch.cuda.is_available():
        x.to('cuda')
    return x

#Cell
def mkdir(directory):
    if not os.path.exists(directory):
        os.makedirs(directory)